import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Sidebar from "./components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto max-w-[1300px]">
          <Header />
          <div className="flex mt-20 gap-10">
            <Sidebar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
