import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Sidebar from "./components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gtihub Profie Viewer",
  description: "Generated by create next app",
  icons: ["/images/profile-removebg-preview.png"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto">
          <Header />
        </div>

        <div className="flex md:flex-row flex-col justify-center px-8 mt-20">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
